# Generated by Django 2.0.7 on 2020-08-05 15:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompanyManagement', '0001_initial'),
        ('EmployeeManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('PayslipID', models.UUIDField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('LastModifiedDate', models.DateField(auto_now=True)),
                ('Data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('CompanyID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CompanyManagement.Company')),
                ('EmployeeID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.Employee')),
            ],
        ),
    ]
