# Generated by Django 3.0.8 on 2020-08-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyManagement', '0001_initial'),
        ('EmployeeManagement', '0002_auto_20200805_1250'),
        ('PayslipManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='CompanyID',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='CompanyManagement.Company'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='EmployeeID',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.Employee'),
        ),
    ]
