# Generated by Django 3.0.8 on 2020-08-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0001_initial'),
        ('ManagerManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='AccountNumber',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='CompanyID',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='EmailAddress',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='PersonnelCode',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='Token',
        ),
        migrations.AddField(
            model_name='manager',
            name='EmployeeID',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.Employee'),
        ),
        migrations.AddField(
            model_name='manager',
            name='id',
            field=models.AutoField(auto_created=True, default='exit', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
