# Generated by Django 3.0.8 on 2020-08-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0001_initial'),
        ('ManagerManagement', '0003_auto_20200804_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='EmployeeID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.Employee'),
        ),
    ]
