# Generated by Django 3.0.8 on 2020-08-05 20:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompanyManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('PersonnelCode', models.DecimalField(decimal_places=0, max_digits=10)),
                ('AccountNumber', models.DecimalField(decimal_places=0, max_digits=16)),
                ('PhoneNumber', models.DecimalField(decimal_places=0, max_digits=10)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('Token', models.CharField(blank=True, max_length=16, null=True)),
                ('CompanyID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CompanyManagement.Company')),
            ],
        ),
    ]
