# Generated by Django 2.0.7 on 2020-08-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompanyManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.UUIDField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('PersonnelCode', models.DecimalField(decimal_places=0, max_digits=10)),
                ('AccountNumber', models.DecimalField(decimal_places=0, max_digits=10)),
                ('PhoneNumber', models.DecimalField(decimal_places=0, max_digits=10)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('Token', models.CharField(max_length=200)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyManagement.Company')),
            ],
        ),
    ]
