# Generated by Django 3.0.8 on 2020-08-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(default='1234', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PersonnelCode',
            field=models.DecimalField(decimal_places=0, max_digits=10, unique=True),
        ),
    ]
