# Generated by Django 2.0.7 on 2020-08-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FormManagement', '0001_initial'),
        ('ManagerManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ID', models.UUIDField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('MaxEmployee', models.DecimalField(decimal_places=0, max_digits=10)),
                ('FormID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormManagement.Form')),
                ('ManagerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerManagement.Manager')),
            ],
        ),
    ]
