# Generated by Django 3.0.8 on 2020-08-05 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('MaxEmployee', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
