# Generated by Django 3.0.8 on 2020-08-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ID', models.UUIDField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('MaxEmployee', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
